### ISSUE TITLE
Launch an ap endpoint

### ISSUE THREAD

**Issue by Ganime422** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#144]
Hi there
I'm trying to understand what was the endpoint you used in order to launch an app after you have set the app id?
if you would like to launch the disney+ app for example.

thanks!

**Comment by RogerSelwyn** [comment]
It's just a matter of button presses, there is no api endpoint I am aware of. So go to a known starting point (perhaps using Sky button, then down, down, right, select, etc) Just like using the physical remote.

**Comment by Ganime422** [comment]
I see, but with the voice remote, I can use and it opens netflix right away, so I guess there is some way, no?

**Comment by RogerSelwyn** [comment]
Possibly, possibly not. Sky do not publish any api so it isn't possible to tell. With voice it is going through some voice recognition software (which may too may not be done on the Sky box), which is then telling the box to launch the app. So clearly the box already knows how to launch the app, because you can select it using buttons and it runs, but that doesn't mean there is an api endpoint for it. Not all the capabilities of the device need to be exposed via an api.

**Comment by RogerSelwyn** [comment]
Possibly there is an api endpoint for sending the voice command, but there may not be also. The voice controller is Bluetooth, so likely the voice is sent via that method.

**Comment by Ganime422** [comment]
so maybe there is also a way to control it through bluetooth?

**Comment by RogerSelwyn** [comment]
Maybe, but not with me doing it. I don't plan to learn a new protocol completely guessing at Sky implementation.
