### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by michaeldjjohnson** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#153]
My BT router loves clashing with my SKY Q device. I have given a dedicated IP address to my SKY Q device but often enough I lose connection with it as my BT router wants to give it a different IP address. Therefore this becomes useless within my Home Assistant.

Is there a way where I can use the MAC address of the SKY Q device instead of it's IP address so that I have more stability and not reliant upon IP addresses alone?

**Comment by RogerSelwyn** [comment]
Sorry no an IP is required. You can try using the name it is known as on the router (e.g. skyq.local), but I guess if your BT router can't manage DHCP then it is unlikely to get the DNS right either. To achieve mac address to IP lookup involves a whole level of complexity (arp table lookup) that is really just dealing with the vagaries of your network, and should not be required. 

 I believe you can set a static IP address on the SkyQ box itself, which if you also reserve it on the router will mean it won't get re-used. I find it all works best over a wired connection, rather than wireless. Personally I use Devolo Powerline to achieve that.

**Comment by michaeldjjohnson** [comment]
Thank you for taking the time out and effort to reply to me. I will try your suggestions. Thank you Roger
