### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NicolaContin** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#168]
### Describe the bug

Host connection impossibile

<img width="576" alt="Screenshot 2024-03-17 alle 22 18 41" src="https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/26112814/cf5a407a-50e7-415f-9f65-7868b55d8329">
<img width="637" alt="Screenshot 2024-03-17 alle 22 19 22" src="https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/26112814/7184c164-ed88-472d-a97e-4743b9ad446e">

<img width="462" alt="Screenshot 2024-03-17 alle 22 28 25" src="https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/26112814/7a94a9f9-8ca2-4f59-8e97-1e5d2d955b20">

### To reproduce

Host connection impossibile

### Expected bahavior

Host connection impossibile

### What version of SkyQ has the issue?

v2.11.7

### What version of Home Assistant Core has the issue?

core-2024.3.1

### Configuration type

UI

**Comment by RogerSelwyn** [comment]
Multiple questions:

- As far as I am aware a SkyQ box does not respond to ICMP/ping, are you sure you aren't trying to connect to some other device? 
- What type of SkyQ box do you have? If it is not a satellite box and is internet only it will not work?
- Try using this url and post the response - http://192.168.178.135:9006/as/system/information
- Are there any errors in the logs? You have not responded to that question, rather than saying no.

**Comment by NicolaContin** [comment]
Many thanks for the reply

As far as I know, a SkyQ box doesn't respond to ICMP/ping, are you sure you're not trying to connect to some other device?ccc
**100% safe, I created a dedicated wifi network from UniFi and only connected the SkyQ box to it**

What type of SkyQ box do you have? If it's not a satellite receiver and it's just Internet, it won't work?
**I have the SkyQ with also the Antenna connector, I can't tell you the model but I'll attach a photo of the back**
<img width="684" alt="Screenshot 2024-03-17 alle 22 51 18" src="https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/26112814/7e58d509-cbf2-4c92-8db0-712655cee4b4">


Try using this URL and post the answer: http://192.168.178.135:9006/as/system/information
**I don't get any response, it just keeps loading**

Are there errors in the logs? You didn't answer that question, instead saying no.
**I don't know where to look at the logs**

**Comment by RogerSelwyn** [comment]
That looks to be a Sky Steam device - https://assistenza.sky.it/sky-glass/guida-installazione-e-attivazione-stream - which is not supported by the integration.

**Comment by NicolaContin** [comment]
is this https://assistenza.sky.it/sky-q/via-internet/guida-attivazione-sky-q-via-internet

**Comment by RogerSelwyn** [comment]
They may call it Sky Q in Italy, but it is a Sky Stream box that I linked to. I understand there is a coax aerial (not satellite) because that is a legal requirement in Italy, but it is in essence an internet based box which as noted on the home page of this GitHub is not supported by the integration.
