### ISSUE TITLE
[BUG]  THE CHANNEL LIST DOES NOT UPDATE

### ISSUE THREAD

**Issue by giugit** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#173]
### Describe the bug

In my configuration, there are 1 SKYQ and 2 SKY mini devices. They are all recognized, but once the channels are selected, the 3 players always show channels from a previous configuration.

I have already uninstalled and reinstalled the integration, making sure to delete the entire SKYQ directory inside the custom component first.

But the problem is not resolved.

What could it depend on?

Where are the channels I select in the configuration stored?

Thank you.

### To reproduce

In my configuration, there are 1 SKYQ and 2 SKY mini devices. They are all recognized, but once the channels are selected, the 3 players always show channels from a previous configuration.

I have already uninstalled and reinstalled the integration, making sure to delete the entire SKYQ directory inside the custom component first.

But the problem is not resolved.

What could it depend on?

Where are the channels I select in the configuration stored?

Thank you.

### Expected bahavior

In my configuration, there are 1 SKYQ and 2 SKY mini devices. They are all recognized, but once the channels are selected, the 3 players always show channels from a previous configuration.

I have already uninstalled and reinstalled the integration, making sure to delete the entire SKYQ directory inside the custom component first.

But the problem is not resolved.

What could it depend on?

Where are the channels I select in the configuration stored?

Thank you.

### What version of SkyQ has the issue?

V2.11.10

### What version of Home Assistant Core has the issue?

core-2024.9.2

### Configuration type

UI

**Comment by RogerSelwyn** [comment]
You haven’t included your configuration as requested in the issue template, so I’m trying to envisage what you really mean. 

What do you mean by ‘once the channels are selected’? Where do the ‘players always show channels from a previous configuration’?

When you install and reinstall the integration, do you mean from HACS or from the devices panel in HA settings? For reference, deleting the code (from custom components) will not delete the device/entity configuration because that is stored in the .storage directory with all other HA config. For the configuration of the SkyQ box, it pulls the channel list directly from the box itself, so have you tried updating your chosen channel list in the UI?

**Comment by giugit** [comment]
<img width="770" alt="ConfSKY - Copia" src="https://github.com/user-attachments/assets/dc69ba9b-1cbc-457a-b870-781d06a9b45a">
<img width="554" alt="SKYPLAYER - Copia" src="https://github.com/user-attachments/assets/3ea0a7a5-e018-4e72-b4bc-17def99e6548">


The channels I select in the configuration are not updated in the player, which always shows an old list as seen in the images.

I’m not sure if this is enough to help you understand the problem.

**Comment by RogerSelwyn** [comment]
Those look to be different boxes. One is ‘Sky Q’, the other is ‘skyq sala’. I don’t have a Sky Q box that I can develop against anymore (it just cost too much), so I can’t easily check the naming in those two dialogues, but I don’t think you are considering the same thing. 

However I have just tested against my one live box and it worked fine. You can check the channel list in Developer Tools/States.

**Comment by giugit** [comment]
<img width="1834" alt="SkyListaCanali" src="https://github.com/user-attachments/assets/6631b455-f132-4c1b-b9c8-5ee54bd24ec6">

This list is an old list and does not correspond to the one I selected in the configuration.

**Comment by RogerSelwyn** [comment]
I’ve would suggest you delete on SkyQ integration instances, you don’t need to uninstall from HACS. The check in .storage/config_entries.json that they have all been removed. Then check in Developer tools to make sure they have all been removed. If they are still showing refresh your browser cache and re-check. Also make sure you haven’t set them up via yaml. Those entities currently showing in Developer tools have no makes, which makes me think there is something of with them.

**Comment by giugit** [comment]
In this file core.config.entries, the list of channels is stored correctly. I don’t know where the player is reading the wrong list from. I couldn’t find anything, and honestly, I didn’t quite understand your suggestions. Thank you.

**Comment by RogerSelwyn** [comment]
Have you configured the SkyQ integration via configuration.yaml previously?

This should help you with you to delete a configuration instance. 

![image](https://github.com/user-attachments/assets/6d7674a7-2d72-4fcf-a01b-f6dbf0584c1f)


Once you have deleted them and checked in Developer tools, which since you have shown me screen shots from there you clearly know how to access, then you should be able to identify if you have it installed via config.yaml.

**Comment by giugit** [comment]
I have already done the following operations previously:

Uninstalled SkyQ as you indicated
Manually deleted the old YAML configurations that were present
Reinstalled SkyQ from HACS
Now there is nothing in the config YAML that refers to SkyQ, yet the channel list is still the old one.

It’s a real mystery!

**Comment by RogerSelwyn** [comment]
I would uninstall from hacs, ensure code has gone, then reboot HA, and look at the logs. If there is anything left in there HA will complain and probably tell you where.

**Comment by giugit** [comment]
Resolved inside the config there was  media_player: !include media_players.yaml where there was an old configuration that was being read with priority. Thanks for the inspiration, the help, and the availability. Your integration is very well done! Thanks again
