### ISSUE TITLE
[Feature Request] EPG for Sky Q Germany

### ISSUE THREAD

**Issue by bluenazgul** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#29]
**Describe the solution you'd like**  
EPG for Sky Q Germany - https://www.sky.de/tvguide-7599

**Additional context**  
I dont know if this would help to add an EPG for Sky Q Germany - the only EPG i was able to find it the official Sky Website from Germany

**Comment by RogerSelwyn** [comment]
For this I would need a url where the epg can be returned in programmatic form, website link to the sky programme guide is not sufficient. I also need a url where all the channel images can be found. This is less important but adds to the look of it. 

I'm afraid I don't speak/read German, so I will need someone who can to do some research.

**Comment by RogerSelwyn** [comment]
@bluenazgul - Can you run this query against the IP address of your box, and provide me a subset of the response (I suspect the whole think will be to big).

**Comment by RogerSelwyn** [comment]
I've done much of the work for this, but I need the query I requested, so I can validate that I'm looking at the data correctly.

**Comment by bluenazgul** [comment]
> @bluenazgul - Can you run this query against the IP address of your box, and provide me a subset of the response (I suspect the whole think will be to big).

could you point me to the query command you mean? I will try to help as much as i can, but iam not an develeoper, only advanced user and new to HA

**Comment by RogerSelwyn** [comment]
Oops, I thought I put it in my previous post. I’ll post it later.

**Comment by bluenazgul** [comment]
take your time....

**Comment by RogerSelwyn** [comment]
This is it, just change the IP to the one for your sky box http://192.168.1.22:9006/as/services. You can just do it from any browser.

**Comment by bluenazgul** [comment]
https://pastebin.com/G63vzRKu hope this helps

**Comment by RogerSelwyn** [comment]
Ok, that helps. I probably won't get this finished tomorrow, and then I'm away for a week, so it may have to wait a little.

**Comment by bluenazgul** [comment]
no problem, take your time, its only a hobby

**Comment by RogerSelwyn** [comment]
At the moment I have a missing link (as I did for Italy). I can get what channel the box thinks it is on, but the EPG uses a different identifier to get the programme listings. For Italy someone provided me a page I could get the connection from, but I don't have that for Germany. (UK is easy because they all use the same identifier). 

So at the moment I can tell you what channel you are on, but can't provide a channel image or what programme is being watched.

**Comment by bluenazgul** [comment]
The Channels Names are working correct with the current release, whats not working is whats playing (on some channels its shows incorrect infos (RTL and RTL2) the others are unknown)

**Comment by RogerSelwyn** [comment]
If it shows anything it will show what is on for U.K. SkyQ, it will default to GBR if it doesn't know the country the box tells it (should be DEU for your box).

**Comment by bluenazgul** [comment]
Correct:

Protokolldetails ( WARNING )
Logger: pyskyqremote.skyq_remote
Source: /usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py:671
First occurred: 14:46:04 (1 occurrences)
Last logged: 14:46:04

W0030 - Invalid country, defaulting to GBR : 192.168.178.132 : DEU : No module named 'pyskyqremote.country.remote_de'

**Comment by bluenazgul** [comment]
If You need anything to try out or test, please let me know - i try to help

**Comment by RogerSelwyn** [comment]
I've done most of the coding work on this, however unfortunately a lookup table needs to be created to match the channels in the list your sent by pastern, with the channels in the EPG. I'm not sure how many channels there are on Sky Germany but I imagine it is a few hundred, and it will need maintenance (unless we can find somewhere else that provides it).

You can test it by changing the requirements line in manifest.json. the pyskyqremote version needs to be 0.2.31b1.

This uses a lookup which is hosted here - https://github.com/RogerSelwyn/skyq_remote/blob/master/pyskyqremote/country/channels-de.json - only channels 100 and 101 are currently set up. In actual fact it uses the 'sid' for lookup, which you can find in the channel list you gave me, since I think channel numbers can changes, but SIDs don't.

**Comment by bluenazgul** [comment]
Nice, seems to work here

100 - Sky One HD
![image](https://user-images.githubusercontent.com/171537/96024322-ddba9880-0e53-11eb-8b42-7b86d0f2afd9.png)
![image](https://user-images.githubusercontent.com/171537/96024561-2e31f600-0e54-11eb-9724-da8cddb9ea63.png)

101 - Sky Serien & Shows HD
![image](https://user-images.githubusercontent.com/171537/96024438-02af0b80-0e54-11eb-979e-6698b0c6fafe.png)
![image](https://user-images.githubusercontent.com/171537/96024594-3be77b80-0e54-11eb-9954-dba5ef7902aa.png)

**Comment by bluenazgul** [comment]
just made  a pull request for hthe channels-de.json - added most HD Channels excluding Sport Channels and Private Channels (as they are missing inside the SKY EPG at the website.

**Comment by RogerSelwyn** [comment]
Let me check it out in the morning. In the middle of something now.

**Comment by RogerSelwyn** [comment]
There is a list here, but not sure your missing ones are on there - https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/siteini.pack/Germany/sky.de.channels.xml

**Comment by bluenazgul** [comment]
sadly there are also only the same Channels like on the website, but here https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/siteini.pack/Germany/tvdigital.de.channels.xml are most of the Channels listed, but not with the Sky SID

**Comment by RogerSelwyn** [comment]
Unfortunately that will be for the TV Digital service, not Sky. 😞

**Comment by bluenazgul** [comment]
sadly yes, the Sky EPG is realy only showing Sky Channels and not the Free Standard Channels

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.4.4
