### ISSUE TITLE
HomeKit Pairing Fails when device class set to TV

### ISSUE THREAD

**Issue by SparkyDan555** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#64]
Pairing with HomeKit (as an accessory, not a bridge) works when device class is left as default and Sky Q is added to the home app as a series of switches, however when it is set to "tv" in order to enable the control centre remote control, HomeKit pairing fails with the message "Accessory is out of compliance".

**Comment by RogerSelwyn** [comment]
Sorry, no screenshots attached.

**Comment by RogerSelwyn** [comment]
I've looked at this even more, and to be honest I don't think it can be made to work even at a fairly basic level for volume controls. Partly this is because of how the HomeKit integration works. It queries the capabilities of specified Media Players when they start-up. The SkyQ integration queries the Volume Entity media player to see if it is switched on, and if so it adds volume control capabilities to the SkyQ integration. 

Well, the volume entity media player may not be switched on or it may not be available as an entity (yet) at HA startup, therefore SkyQ does not present volume capabilities to HomeKit and therefore HomeKit won't configure up the device properly for Apple.

This is further confused by the fact that whilst the volume entity may be switched on and available at start-up (and therefore HomeKit sets up correctly), it may be switched off later whilst SkyQ is switched on, and then HomeKit will try and control volume for it when it can't.

All told, I think you should treat the SkyQ box as a decoder in HomeKit, not as a TV. It isn't a TV and the fact that it has some similar capabilities is just confusing things.

I'm therefore going to close this ticket as cannot be resolved.

**Comment by RogerSelwyn** [comment]
Despite what I have stated here, I have now added functionality to make the buttons work in the Apple Remote app. The arrows, will go left/right/up/down within the guide. i opens the guide, back does a dismiss, centre button does a select. Volume can be changed using your phone/tablet volume controls (not something I have specifically enabled, but is there by default and works on my iPad).

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.6.10b4

**Comment by RogerSelwyn** [comment]
A thought, I've not tried without some sources setup, so maybe worth looking at that. I'm considering adding the current source if not in the list, so it shows correctly in Apple Home.

**Comment by RogerSelwyn** [comment]
Have you tried going back to the version that worked for you? The only thing that would 'visibly' change is that I have added the current source to the source_list. It all works fine for me. My iPad/iPhone are on latest iOS 15

**Comment by RogerSelwyn** [comment]
You should be able to compare what HomeKit sees by looking in developer tools. Maybe worth posting a screenshot of that when it shows out if compliance.

**Comment by RogerSelwyn** [comment]
If it goes wrong after a reboot, then take a screen capture of the entity in developer tools, and I'll take a look at what might be causing the problem.

**Comment by RogerSelwyn** [comment]
Final release of this version - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.6.10
