### ISSUE TITLE
[Feature Request] Add automation / blueprint to switch to HD version of channel

### ISSUE THREAD

**Issue by mark007** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#72]
**Is your feature request related to a problem? Please describe.**  
I have noticed while we have purchased a lovely 4K screen for the living room, many people in the house have a habit of switching to the non HD channels :) This drives me crazy as we have to then find the HD version of it which may be hundreds of channels away.

I have created a quite crude automation to fix this, which is possibly quite tied to my particular setup. I basically painstakingly added the hd channel names (i named them as the sd name + ' HD') and numbers to the skyq integration and when I detect the channel changing, if the integration source list has the HD channel name, i switch to it.

**Describe the solution you'd like**  
I wonder can something like this be somehow packaged up with the integration as how I have done it was quite crude and slow to set up.

**Describe alternatives you've considered**  

**Additional context**

**Comment by RogerSelwyn** [comment]
Hi Mark, thanks for the idea, but I would not intend to start creating the integration as an automation platform. Node Red or HAs own automation capabilities are perfectly adequate for this. Have you considered using favourites on your SkyQ box to make the HD channels more accessible?

As a matter of interest the channel list is available via a simple rest api call to the Sky Q box, so using Node Red you could do a simple lookup of all channels as a setup, then do a lookup of the channel changed to ( + HD) to see if it exists in the complete list and then change to it. Probably not as simple as that, because I bet the names don't match across, but certainly the channel numbers are available in the list, so some level of automation could be done.

**Comment by mark007** [comment]
Thanks for the quick reply and the great ideas. Yes as many channels didnt match the sd name + ' HD' I had to go this route. Ill foe sure check the api you mentioned and see how automated I can make it. I guess Ill see at that point if I could package it up if others want to use it.

**Comment by RogerSelwyn** [comment]
You won't find any public api documentation, much of what the integration is built on is existing code (I forked from a previous creator), plus ongoing research for other peoples learnings about the api, and some leaps of understanding.

This will get you the channel list:-
- http://192.168.1.122:9006/as/services
- c is the channel number
- sid is the main key for correlating to other apis
- There is also http://192.168.1.122:9006/as/services/{sid}

This will get you favourites (I found this one from some Homebridge code recently):
- http://192.168.1.122:9006/as/services/favourites
- Use sid as lookup

This will get you your recordings:-
- http://192.168.1.122:9006/as/pvr/?limit=1000&offset=0
- http://192.168.1.122:9006/as/pvr/details/{pvrid}

**Comment by mark007** [comment]
Fantastic!!! Thanks very much!!!
