### ISSUE TITLE
[BUG] ? cannot iinstall integration

### ISSUE THREAD

**Issue by MagicMilamber** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#99]
I Install with HACS. 
Files are in folder custom Component.

But when I try to integrate the integration is not found.

My misstake or really an error ?

**Comment by RogerSelwyn** [comment]
Assuming you have rebooted HASS, I'm afraid that sometimes HASS does not seem to always pick up a new integration first time round (or even second or third). I don't know what the cause is, but I've had it happen it's custom components before. Eventually it will work, but I don't know what will trigger it sorting itself out.

**Comment by MagicMilamber** [comment]
Hello Roger,

After reboot the Server completly it works now. 
A little bit cazy but who cares ;)

Thanks for you Support
